<div class="user-component">

<h1>Usuários</h1>


    <div class="user-list-component">
        <table class="table table-hover user-list">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Usuário</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Email</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                <tr class="empty">
                    <td colspan="5">Carregando Usuários...</td>
                </tr>
            </tbody>
        </table>
    </div>

    <hr>
    <div class="user-add-component text-left">
        <h2>Adicionar Usuário</h2>
        <form action="admin/user" method="post" class="form-user-add">
            <div class="form-group">
                <label for="user-name">Nome</label>
                <input type="text" name="user[name]" id="user-name" value="" required class="form-control">
            </div>
            <div class="form-group">
                <label for="user-email">Email</label>
                <input type="email" name="user[email]" id="user-email" value="" required class="form-control">
            </div>
            <div class="form-group">
                <label for="user-user">Nome de Usuário</label>
                <input type="text" name="user[user]" id="user-user" value="" required class="form-control" minlength="6">
            </div>
            <div class="form-group">
                <label for="user-password">Senha</label>
                <input type="password" name="user[password]" id="user-password" value="" required class="form-control" minlength="6">
            </div>
            <button type="submit" class="btn btn-success mb-2">Adicionar</button>
        </form>
    </div>

</div>