<?php if ($error) : ?>
<div class="alert alert-danger" role="alert">
    <?php echo $error; ?>
</div>
<?php endif; ?>

<?php $this->protectedIncludeScope($this->templatePath . '/components/scoreboard.phtml', [ 'csrf' => $csrf ]); ?>

<hr>

<div class="row rounds-component">
  <div class="col-12">
    <h2>Etapas</h2>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#rounds-masc" role="tab" aria-controls="home" aria-selected="true">Masculino</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#rounds-mix" role="tab" aria-controls="profile" aria-selected="false">Misto</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="rounds-masc" class="tab-pane fade show active p-4 border border-top-0" role="tabpanel" aria-labelledby="profile-tab">
          <?php $this->protectedIncludeScope($this->templatePath . '/components/scoreboard-round.phtml', [ 'csrf' => $csrf, 'type' => 'masc' ]); ?>
      </div>
      <div id="rounds-mix" class="tab-pane fade p-4 border border-top-0" role="tabpanel" aria-labelledby="profile-tab">
          <?php $this->protectedIncludeScope($this->templatePath . '/components/scoreboard-round.phtml', [ 'csrf' => $csrf, 'type' => 'mix' ]); ?>
      </div>
    </div>
  </div>
</div>

<hr>

<?php $this->protectedIncludeScope($this->templatePath . '/components/gallery.phtml', [ 'csrf' => $csrf ]); ?>