<?php if ($error) : ?>
<div class="alert alert-danger" role="alert">
    <?php echo $error; ?>
</div>
<?php endif; ?>

<?php $this->protectedIncludeScope($this->templatePath . '/components/scoreboard.phtml', [ 'csrf' => $csrf ]); ?>

<hr>

<?php $this->protectedIncludeScope($this->templatePath . '/components/scoreboard-rounds.phtml', [ 'csrf' => $csrf ]); ?>

<hr>

<?php $this->protectedIncludeScope($this->templatePath . '/components/gallery.phtml', [ 'csrf' => $csrf ]); ?>