<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin - Copa Champagnat - Província Marista Brasil Centro-Sul</title>

    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto&display=swap" rel="stylesheet" type="text/css" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.css" rel="stylesheet" type="text/css" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" rel="stylesheet" type="text/css" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" rel="stylesheet" type="text/css" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css" rel="stylesheet" type="text/css" crossorigin="anonymous">

    <link href="<?php echo $helpers->pathJoin($siteUrl, 'assets/css/admin.css'); ?>" rel="stylesheet" type="text/css">
</head>
<body>
<div id="app" class="container-fluid d-flex align-items-center">
  <div class="container rounded">
      <header class="row">
          <div class="col-10">
              <h1>Copa Champagnat - Admin</h1>
          </div>
          <div class="col-2">
            <?php if ($isUserLoggedIn) : ?>
            <a href="<?php echo $helpers->pathJoin($siteUrl, '/admin/logout'); ?>">Logout</a>
            <?php endif; ?>
          </div>
      </header>
      <div class="row">
          <main class="col">
              <?php echo $content; ?>
          </main>
      </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/URI.js/1.19.1/URI.min.js" crossorigin="anonymous"></script>
<script src="<?php echo $helpers->pathJoin($siteUrl, 'assets/js/jquery.serialize-object.js'); ?>"></script>

<script src="<?php echo $helpers->pathJoin($siteUrl, 'assets/js/admin.js'); ?>"></script>
<script>
  var siteUrl = '<?php echo $siteUrl; ?>';
  var apiUrl = '<?php echo $apiUrl; ?>';
  var CSRFRequest = <?php echo json_encode([
    'name' => "{$csrf['name'][0]}={$csrf['name'][1]}",
    'value' => "{$csrf['value'][0]}={$csrf['value'][1]}",
  ]); ?>
</script>
</body>
</html>
