<div class="login-component">
    <form action="admin/login" method="post">
        <input type="hidden" name="<?php echo $csrf['name'][0]; ?>" value="<?php echo $csrf['name'][1]; ?>">
        <input type="hidden" name="<?php echo $csrf['value'][0]; ?>" value="<?php echo $csrf['value'][1]; ?>">

        <div class="form-group row no-gutters">
            <label for="login-email" class="col-sm-3 col-form-label text-right pr-2">Usuário/Email</label>
            <div class="col-sm-9">
              <input type="text" class="form-control" id="login-email" name="email" value="" required>
            </div>
        </div>
        <div class="form-group row no-gutters">
          <label for="login-password" class="col-sm-3 col-form-label text-right pr-2">Senha</label>
          <div class="col-sm-9">
            <input type="password" class="form-control" id="login-password" name="password" value="" required>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>